-- Step 1: multi-hotel schema and safe migration of existing single-hotel data.
-- Run this file once in Supabase SQL Editor before the workflow and RLS files.

create extension if not exists btree_gist;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'hotel_role') then
    create type public.hotel_role as enum (
      'owner',
      'manager',
      'front_desk',
      'finance'
    );
  end if;
end
$$;

create table if not exists public.hotels (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  location text not null default '',
  timezone text not null default 'UTC',
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  "fullName" text,
  email text,
  avatar text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.hotel_members (
  id bigint generated by default as identity primary key,
  "hotelId" bigint not null references public.hotels(id) on delete cascade,
  "userId" uuid not null references public.profiles(id) on delete cascade,
  role public.hotel_role not null default 'front_desk',
  created_at timestamptz not null default now(),
  unique ("hotelId", "userId")
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, "fullName", email, avatar)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'fullName', ''),
    new.email,
    coalesce(new.raw_user_meta_data ->> 'avatar', '')
  )
  on conflict (id) do update
  set email = excluded.email,
      "fullName" = coalesce(nullif(excluded."fullName", ''), profiles."fullName");
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email, raw_user_meta_data on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles (id, "fullName", email, avatar)
select
  id,
  coalesce(raw_user_meta_data ->> 'fullName', ''),
  email,
  coalesce(raw_user_meta_data ->> 'avatar', '')
from auth.users
on conflict (id) do update
set email = excluded.email,
    "fullName" = coalesce(nullif(excluded."fullName", ''), profiles."fullName");

insert into public.hotels (name, slug, location, timezone)
values ('The Wild Oasis', 'the-wild-oasis', 'Default hotel', 'Asia/Shanghai')
on conflict (slug) do nothing;

alter table public.cabins add column if not exists "hotelId" bigint;
alter table public.bookings add column if not exists "hotelId" bigint;
alter table public.guests add column if not exists "hotelId" bigint;
alter table public.settings add column if not exists "hotelId" bigint;

do $$
declare
  default_hotel_id bigint;
begin
  select id into default_hotel_id
  from public.hotels
  where slug = 'the-wild-oasis';

  update public.cabins set "hotelId" = default_hotel_id where "hotelId" is null;
  update public.bookings set "hotelId" = default_hotel_id where "hotelId" is null;
  update public.guests set "hotelId" = default_hotel_id where "hotelId" is null;
  update public.settings set "hotelId" = default_hotel_id where "hotelId" is null;

  insert into public.hotel_members ("hotelId", "userId", role)
  select default_hotel_id, id, 'owner'::public.hotel_role
  from public.profiles
  on conflict ("hotelId", "userId") do nothing;
end
$$;

alter table public.cabins alter column "hotelId" set not null;
alter table public.bookings alter column "hotelId" set not null;
alter table public.guests alter column "hotelId" set not null;
alter table public.settings alter column "hotelId" set not null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'cabins_hotel_id_fkey') then
    alter table public.cabins
      add constraint cabins_hotel_id_fkey
      foreign key ("hotelId") references public.hotels(id) on delete restrict;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'bookings_hotel_id_fkey') then
    alter table public.bookings
      add constraint bookings_hotel_id_fkey
      foreign key ("hotelId") references public.hotels(id) on delete restrict;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'guests_hotel_id_fkey') then
    alter table public.guests
      add constraint guests_hotel_id_fkey
      foreign key ("hotelId") references public.hotels(id) on delete restrict;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'settings_hotel_id_fkey') then
    alter table public.settings
      add constraint settings_hotel_id_fkey
      foreign key ("hotelId") references public.hotels(id) on delete cascade;
  end if;
end
$$;

create unique index if not exists settings_one_row_per_hotel
  on public.settings ("hotelId");
create unique index if not exists cabins_id_hotel_unique
  on public.cabins (id, "hotelId");
create unique index if not exists guests_id_hotel_unique
  on public.guests (id, "hotelId");
create index if not exists cabins_hotel_id_idx on public.cabins ("hotelId");
create index if not exists bookings_hotel_dates_idx
  on public.bookings ("hotelId", "startDate", "endDate");
create index if not exists guests_hotel_id_idx on public.guests ("hotelId");
create index if not exists hotel_members_user_id_idx
  on public.hotel_members ("userId");

create table if not exists public.maintenance_blocks (
  id bigint generated by default as identity primary key,
  "hotelId" bigint not null references public.hotels(id) on delete cascade,
  "cabinId" bigint not null references public.cabins(id) on delete cascade,
  "startDate" date not null,
  "endDate" date not null,
  reason text not null,
  "createdBy" uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  constraint maintenance_dates_valid check ("endDate" > "startDate")
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'bookings_cabin_same_hotel_fkey'
  ) then
    alter table public.bookings
      add constraint bookings_cabin_same_hotel_fkey
      foreign key ("cabinId", "hotelId")
      references public.cabins(id, "hotelId") on delete restrict;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'bookings_guest_same_hotel_fkey'
  ) then
    alter table public.bookings
      add constraint bookings_guest_same_hotel_fkey
      foreign key ("guestId", "hotelId")
      references public.guests(id, "hotelId") on delete restrict;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'maintenance_cabin_same_hotel_fkey'
  ) then
    alter table public.maintenance_blocks
      add constraint maintenance_cabin_same_hotel_fkey
      foreign key ("cabinId", "hotelId")
      references public.cabins(id, "hotelId") on delete cascade;
  end if;
end
$$;

create index if not exists maintenance_hotel_dates_idx
  on public.maintenance_blocks ("hotelId", "startDate", "endDate");

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'maintenance_no_overlap'
  ) then
    alter table public.maintenance_blocks
      add constraint maintenance_no_overlap
      exclude using gist (
        "hotelId" with =,
        "cabinId" with =,
        daterange("startDate", "endDate", '[)') with &&
      );
  end if;
end
$$;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  "hotelId" bigint not null references public.hotels(id) on delete cascade,
  "actorId" uuid references public.profiles(id) on delete set null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  "resourceType" text not null,
  "resourceId" text not null,
  "beforeData" jsonb,
  "afterData" jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_hotel_created_idx
  on public.audit_logs ("hotelId", created_at desc);
